# Generated by Django 5.1.2 on 2025-05-22 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macrociclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total_dias', models.PositiveIntegerField()),
                ('num_semanas', models.PositiveIntegerField()),
                ('porcentaje_acumulacion', models.PositiveIntegerField()),
                ('porcentaje_transformacion', models.PositiveIntegerField()),
                ('porcentaje_realizacion', models.PositiveIntegerField()),
                ('repeticiones_acumulacion', models.TextField()),
                ('repeticiones_transformacion', models.TextField()),
                ('repeticiones_realizacion', models.TextField()),
                ('porcentajes_tecnico', models.TextField()),
                ('intensidades', models.TextField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potencia.entrenadores')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_semana', models.PositiveIntegerField()),
                ('iso_anio', models.PositiveIntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('dias_entrenamiento', models.PositiveIntegerField()),
                ('macrociclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='potencia.macrociclo')),
            ],
        ),
    ]
