# Generated by Django 5.2.1 on 2025-05-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
