# Generated by Django 5.1.2 on 2025-05-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0002_macrociclo_semana'),
        ('potencia', '0003_remove_profile_foto_profile_foto_perfil'),
    ]

    operations = [
    ]
